CREATE TABLE "user" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(255),
  "email" VARCHAR(255) UNIQUE,
  "password" VARCHAR(255), -- non-hashed of course :)
  "address" TEXT
);

CREATE TABLE "product" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "description" TEXT,
  "price" DECIMAL(10, 2),
  "quantity" INT
);

CREATE TABLE "order" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "order_date" DATE,
  "total_amount" DECIMAL(10, 2),
  FOREIGN KEY ("user_id") REFERENCES "user" ("user_id")
);

CREATE TABLE order_details (
  "order_details_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" INT,
  "product_id" INT,
  "quantity" INT,
  "price" DECIMAL(10, 2),
  FOREIGN KEY ("order_id") REFERENCES "order" ("order_id"),
  FOREIGN KEY ("product_id") REFERENCES "product" ("product_id")
);


INSERT INTO "user" ("username", "email", "password", "address")
VALUES ('ihorprotsak', 'ihorprotsak@gmail.com', 'ihorprotsak', 'Chernivtsi, Ukraine');

INSERT INTO "product" ("name", "description", "price", "quantity")
VALUES ('Product1', 'This is a sample product', 9.99, 100);

INSERT INTO "order" ("user_id", "order_date", "total_amount")
VALUES (1, '2024-01-21', 9.99);

INSERT INTO "order_details" ("order_id", "product_id", "quantity", "price")
VALUES (1, 1, 1, 9.99);


SELECT * FROM "product";

SELECT * FROM "product" WHERE "name" = 'Product1';

SELECT * FROM "product" WHERE "price" > 10.00;

SELECT * FROM "order_details";

SELECT * FROM "order_details" WHERE "order_id" = 1;

SELECT * FROM "order_details" WHERE "product_id" = 1;


SELECT o.*, u.*
FROM "order" o
JOIN "user" u ON o.user_id = u.user_id;

SELECT od.*, p.*
FROM "order_details" od
JOIN "product" p ON od.product_id = p.product_id;

SELECT od.*, o.*, p.*
FROM "order_details" od
JOIN "order" o ON od.order_id = o.order_id
JOIN "product" p ON od.product_id = p.product_id;


TRUNCATE TABLE "order_details" CASCADE;
TRUNCATE TABLE "order" CASCADE;
TRUNCATE TABLE "product" CASCADE;
TRUNCATE TABLE "user" CASCADE;


DROP TABLE "order_details";
DROP TABLE "order";
DROP TABLE "product";
DROP TABLE "user";
